-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE public.addresses_id_seq;

CREATE SEQUENCE public.addresses_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.cart_items_id_seq;

CREATE SEQUENCE public.cart_items_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.carts_id_seq;

CREATE SEQUENCE public.carts_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.categories_id_seq;

CREATE SEQUENCE public.categories_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.enderecos_id_seq;

CREATE SEQUENCE public.enderecos_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.ordered_items_id_seq;

CREATE SEQUENCE public.ordered_items_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.orders_id_seq;

CREATE SEQUENCE public.orders_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.product_images_id_seq;

CREATE SEQUENCE public.product_images_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.products_id_seq;

CREATE SEQUENCE public.products_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.produtos_id_seq;

CREATE SEQUENCE public.produtos_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.users_id_seq;

CREATE SEQUENCE public.users_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;-- public.addresses definição

-- Drop table

-- DROP TABLE public.addresses;

CREATE TABLE public.addresses (
                                  created_at timestamp(6) NOT NULL,
                                  id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                  updated_at timestamp(6) NULL,
                                  user_id int8 NOT NULL,
                                  "version" int8 NULL,
                                  city varchar(255) NOT NULL,
                                  complement varchar(255) NULL,
                                  neighborhood varchar(255) NOT NULL,
                                  "number" varchar(255) NOT NULL,
                                  state varchar(255) NOT NULL,
                                  street varchar(255) NOT NULL,
                                  zip_code varchar(255) NOT NULL,
                                  CONSTRAINT addresses_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_addresses_user_id ON public.addresses USING btree (user_id);


-- public.cart_items definição

-- Drop table

-- DROP TABLE public.cart_items;

CREATE TABLE public.cart_items (
                                   quantity int4 NOT NULL,
                                   cart_id int8 NOT NULL,
                                   created_at timestamp(6) NOT NULL,
                                   id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                   product_id int8 NOT NULL,
                                   updated_at timestamp(6) NULL,
                                   "version" int8 NULL,
                                   CONSTRAINT cart_items_pkey PRIMARY KEY (id),
                                   CONSTRAINT uk_cart_product UNIQUE (cart_id, product_id)
);


-- public.carts definição

-- Drop table

-- DROP TABLE public.carts;

CREATE TABLE public.carts (
                              created_at timestamp(6) NOT NULL,
                              id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                              updated_at timestamp(6) NULL,
                              user_id int8 NOT NULL,
                              "version" int8 NULL,
                              CONSTRAINT carts_pkey PRIMARY KEY (id),
                              CONSTRAINT carts_user_id_key UNIQUE (user_id)
);


-- public.categories definição

-- Drop table

-- DROP TABLE public.categories;

CREATE TABLE public.categories (
                                   created_at timestamp(6) NOT NULL,
                                   id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                   updated_at timestamp(6) NULL,
                                   "version" int8 NULL,
                                   "name" varchar(255) NOT NULL,
                                   CONSTRAINT categories_pkey PRIMARY KEY (id),
                                   CONSTRAINT uk_category_name UNIQUE (name)
);


-- public.categories_products definição

-- Drop table

-- DROP TABLE public.categories_products;

CREATE TABLE public.categories_products (
                                            category_id int8 NOT NULL,
                                            products_id int8 NOT NULL,
                                            CONSTRAINT categories_products_products_id_key UNIQUE (products_id)
);


-- public.enderecos definição

-- Drop table

-- DROP TABLE public.enderecos;

CREATE TABLE public.enderecos (
                                  id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                  bairro varchar(255) NOT NULL,
                                  cep varchar(255) NOT NULL,
                                  cidade varchar(255) NOT NULL,
                                  complemento varchar(255) NULL,
                                  estado varchar(255) NOT NULL,
                                  logradouro varchar(255) NOT NULL,
                                  numero varchar(255) NOT NULL,
                                  user_id int8 NULL,
                                  CONSTRAINT enderecos_pkey PRIMARY KEY (id)
);


-- public.ordered_items definição

-- Drop table

-- DROP TABLE public.ordered_items;

CREATE TABLE public.ordered_items (
                                      price_purchased numeric(38, 2) NOT NULL,
                                      quantity int4 NOT NULL,
                                      created_at timestamp(6) NOT NULL,
                                      id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                      order_id int8 NOT NULL,
                                      product_id int8 NOT NULL,
                                      updated_at timestamp(6) NULL,
                                      "version" int8 NULL,
                                      CONSTRAINT ordered_items_pkey PRIMARY KEY (id)
);


-- public.orders definição

-- Drop table

-- DROP TABLE public.orders;

CREATE TABLE public.orders (
                               address_id int8 NOT NULL,
                               created_at timestamp(6) NOT NULL,
                               id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               updated_at timestamp(6) NULL,
                               user_id int8 NOT NULL,
                               "version" int8 NULL,
                               order_status varchar(255) NOT NULL,
                               CONSTRAINT orders_order_status_check CHECK (((order_status)::text = ANY ((ARRAY['AGUARDANDO_PAGAMENTO'::character varying, 'PAGO'::character varying, 'ENVIADO'::character varying, 'ENTREGUE'::character varying, 'CANCELADO'::character varying])::text[]))),
	CONSTRAINT orders_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_order_status ON public.orders USING btree (order_status);
CREATE INDEX idx_orders_user_id ON public.orders USING btree (user_id);


-- public.product_images definição

-- Drop table

-- DROP TABLE public.product_images;

CREATE TABLE public.product_images (
                                       created_at timestamp(6) NOT NULL,
                                       id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                       product_id int8 NOT NULL,
                                       updated_at timestamp(6) NULL,
                                       "version" int8 NULL,
                                       url varchar(255) NOT NULL,
                                       CONSTRAINT product_images_pkey PRIMARY KEY (id)
);


-- public.products definição

-- Drop table

-- DROP TABLE public.products;

CREATE TABLE public.products (
                                 price numeric(38, 2) NOT NULL,
                                 unit int4 NOT NULL,
                                 category_id int8 NOT NULL,
                                 created_at timestamp(6) NOT NULL,
                                 id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                 updated_at timestamp(6) NULL,
                                 "version" int8 NULL,
                                 "name" varchar(255) NOT NULL,
                                 CONSTRAINT products_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_products_category_id ON public.products USING btree (category_id);
CREATE INDEX idx_products_name ON public.products USING btree (name);


-- public.produtos definição

-- Drop table

-- DROP TABLE public.produtos;

CREATE TABLE public.produtos (
                                 id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                 "name" varchar(255) NOT NULL,
                                 price numeric(38, 2) NOT NULL,
                                 unit int4 NOT NULL,
                                 categoria_id int8 NOT NULL,
                                 CONSTRAINT produtos_pkey PRIMARY KEY (id)
);


-- public.users definição

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
                              created_at timestamp(6) NOT NULL,
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              updated_at timestamp(6) NULL,
                              "version" int8 NULL,
                              email varchar(255) NOT NULL,
                              full_name varchar(255) NOT NULL,
                              password_hash varchar(255) NOT NULL,
                              phone varchar(255) NULL,
                              "role" varchar(255) NOT NULL,
                              CONSTRAINT users_email_key null,
                              CONSTRAINT users_pkey null,
                              CONSTRAINT users_role_check null
);
CREATE INDEX idx_users_email ON public.users (email text_ops);